root_dir: artifacts

data_ingestion:
  root_dir: artifacts\data_ingestion
  download_path: artifacts\data_ingestion\Downloads
  extract_path: artifacts\data_ingestion\ModelNet10
  data_url: https://3dvision.princeton.edu/projects/2014/3DShapeNets/ModelNet10.zip
  zip_file_name: modelnet.zip
